-- New immutable scene IDs: preserve existing project references and administrator overrides.
INSERT INTO "SceneTemplate" ("id", "slug", "name", "description", "category", "previewAssetId", "basePrompt", "negativeConstraints", "allowedModes", "requiredCredits", "isPro", "enabled", "sortOrder", "config", "updatedAt")
VALUES
('ef78bc54-9f6b-4e3c-9d7f-9ba532e4d107', 'waterfront-night', 'Şehir Işıkları', 'Gece kıyısı, ışıklı köprü ve su yansımaları.', 'Şehir', NULL, $prompt$A blue-hour waterfront promenade overlooking a modern skyline and an illuminated suspension bridge. Layer warm window lights behind the subject, with long gold and blue reflections on gently rippled water. Keep architectural verticals straight and bridge cables physically coherent. Light the subject with a soft neutral nearby practical light and subtle cool sky fill; retain a readable face without making it look like daytime. Keep railings and the waterline behind the subject, never intersecting the body.$prompt$, 'No identity replacement, distorted anatomy, brands, random text or documentary claim.', ARRAY['FULL_SCENE','FAN_MOMENT','BACKGROUND_REPLACE']::TEXT[], 0, FALSE, TRUE, 70, NULL, CURRENT_TIMESTAMP),
('ef78bc54-9f6b-4e3c-9d7f-9ba532e4d108', 'coastal-terrace', 'Sahil Günü', 'Turkuaz koyda çiçekli Akdeniz terası.', 'Doğa', NULL, $prompt$A shaded Mediterranean stone terrace above a clear turquoise cove, framed by a wooden pergola and pink bougainvillea. Include restrained linen seating, distant white sailboats and sunlit coastal hills. Use bright natural daylight softened by overhead shade, warm reflected light from stone and realistic blue water bounce. Keep the horizon level, boats distant and the subject at believable terrace scale. Do not place furniture or plants across the face or limbs; avoid artificial tropical oversaturation.$prompt$, 'No identity replacement, distorted anatomy, brands, random text or documentary claim.', ARRAY['FULL_SCENE','FAN_MOMENT','BACKGROUND_REPLACE']::TEXT[], 0, FALSE, TRUE, 80, NULL, CURRENT_TIMESTAMP),
('ef78bc54-9f6b-4e3c-9d7f-9ba532e4d109', 'window-portrait', 'Stüdyo Işığı', 'Koyu fonda pencere ışıklı doğal portre.', 'Portre', NULL, $prompt$A minimal charcoal-gray portrait setting with directional window light from one side and broad, soft architectural shadows on the wall. Keep the eyes clearly visible, gentle catchlights, a soft shadow transition across the face and fine natural skin and hair texture. Separate dark clothing from the background with restrained ambient fill. No new furniture, accessories or decorative props. Preserve the original person's identity; do not borrow the face, age, gender or clothes of a catalogue example.$prompt$, 'No identity replacement, distorted anatomy, brands, random text or documentary claim.', ARRAY['FULL_SCENE','FAN_MOMENT','BACKGROUND_REPLACE']::TEXT[], 1, TRUE, TRUE, 90, NULL, CURRENT_TIMESTAMP),
('ef78bc54-9f6b-4e3c-9d7f-9ba532e4d110', 'neon-drive', 'Neon Gelecek', 'Neon şehirde ıslak zemin ve özgün spor otomobil.', 'Fantastik', NULL, $prompt$An original futuristic waterfront city after rain, with magenta and cyan architectural lights, a distant illuminated bridge and one unbranded dark sports coupe. Place the subject safely beside the parked vehicle, with believable size and contact shadows; never merge the body with the car or its windows. Use directional neon rim light, neutral facial fill and localized reflections on wet pavement rather than a global purple skin tint. Keep vehicle geometry, wheels and perspective coherent. No emblems, readable number plates, racing action or recognizable franchise elements.$prompt$, 'No identity replacement, distorted anatomy, brands, random text or documentary claim.', ARRAY['FULL_SCENE','FAN_MOMENT','BACKGROUND_REPLACE']::TEXT[], 1, TRUE, TRUE, 100, NULL, CURRENT_TIMESTAMP),
('ef78bc54-9f6b-4e3c-9d7f-9ba532e4d111', 'alpine-lake', 'Dağ Gölü', 'Gün batımında dağ gölü ve ahşap kulübe.', 'Doğa', NULL, $prompt$A tranquil alpine lake at sunset, with snow-capped mountains, dense evergreen forest, a small timber cabin with warm windows and a modest wooden jetty. Place the subject on a safe lakeside foreground with a believable ground plane, not floating on the water. Match low warm sunlight from the horizon with cool sky fill, subtle lake reflections and atmospheric depth in distant peaks. Keep the cabin small relative to the landscape and preserve reflected light direction. Render natural rock, timber and water texture without excessive HDR, repeated trees or impossible mountain reflections.$prompt$, 'No identity replacement, distorted anatomy, brands, random text or documentary claim.', ARRAY['FULL_SCENE','FAN_MOMENT','BACKGROUND_REPLACE']::TEXT[], 0, FALSE, TRUE, 110, NULL, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
