import type { Ionicons } from '@expo/vector-icons';
import type { ComponentProps } from 'react';
import type { ImageSourcePropType } from 'react-native';

export type StudioModelLane = 'FAST' | 'PREMIUM';
export type StudioPalette = readonly [string, string];
export type StudioIconName = ComponentProps<typeof Ionicons>['name'];

type StudioCardBase = {
  id: string;
  name: string;
  description: string;
  creditCost: number;
  modelLane: StudioModelLane | null;
  imageSource?: ImageSourcePropType;
  palette: StudioPalette;
  icon: StudioIconName;
};

export type ProductCategory = StudioCardBase & {
  inputMode: 'SINGLE_PRODUCT';
  promptKey: string;
};

export type StudioPreset = StudioCardBase & {
  hdExtraCredits: 2;
  isPremium: boolean;
  promptKey: string;
};

export type FashionScene = StudioPreset & {
  inputMode: 'PERSON_AND_GARMENT';
};

export type NailPreset = StudioPreset & {
  inputMode: 'HAND_PHOTO';
  swatch: StudioPalette;
};

export type StudioModeCard = StudioCardBase & {
  mode: 'product' | 'fashion' | 'nails';
  defaultSceneId?: string;
  defaultPresetId?: string;
};

export const productCategories = [
  {
    id: 'handbag',
    name: 'Çanta',
    description: 'Deri, dikiş ve metal detaylarını koruyan premium ürün çekimi.',
    creditCost: 0,
    modelLane: null,
    imageSource: require('../../../assets/products/ui/categories/handbag.webp'),
    palette: ['#5C4638', '#D7B991'],
    icon: 'bag-handle-outline',
    inputMode: 'SINGLE_PRODUCT',
    promptKey: 'CATEGORY_HANDBAG',
  },
  {
    id: 'shoes',
    name: 'Ayakkabı',
    description: 'Taban, bağcık ve çift simetrisini koruyan katalog karesi.',
    creditCost: 0,
    modelLane: null,
    imageSource: require('../../../assets/products/ui/categories/shoes.webp'),
    palette: ['#C7B9A8', '#F2EEE8'],
    icon: 'footsteps-outline',
    inputMode: 'SINGLE_PRODUCT',
    promptKey: 'CATEGORY_SHOES',
  },
  {
    id: 'food',
    name: 'Yiyecek & İçecek',
    description: 'İştah açıcı ama gerçeğe sadık yiyecek ve içecek fotoğrafı.',
    creditCost: 0,
    modelLane: null,
    imageSource: require('../../../assets/products/ui/categories/food.webp'),
    palette: ['#5E2F1C', '#C88A4B'],
    icon: 'restaurant-outline',
    inputMode: 'SINGLE_PRODUCT',
    promptKey: 'CATEGORY_FOOD_AND_BEVERAGE',
  },
  {
    id: 'cosmetics',
    name: 'Kozmetik',
    description: 'Ambalaj, kapak ve etiketi koruyan temiz beauty çekimi.',
    creditCost: 0,
    modelLane: null,
    imageSource: require('../../../assets/products/ui/categories/cosmetics.webp'),
    palette: ['#B9A994', '#F0E7DB'],
    icon: 'color-palette-outline',
    inputMode: 'SINGLE_PRODUCT',
    promptKey: 'CATEGORY_COSMETICS',
  },
  {
    id: 'furniture',
    name: 'Mobilya & Dekor',
    description: 'Ölçek, malzeme ve perspektifi koruyan iç mekân sunumu.',
    creditCost: 0,
    modelLane: null,
    imageSource: require('../../../assets/products/ui/categories/furniture.webp'),
    palette: ['#725A43', '#D8C3A7'],
    icon: 'bed-outline',
    inputMode: 'SINGLE_PRODUCT',
    promptKey: 'CATEGORY_FURNITURE',
  },
  {
    id: 'jewelry',
    name: 'Takı',
    description: 'Taş sayısı, kesim ve metal rengini koruyan makro çekim.',
    creditCost: 0,
    modelLane: null,
    imageSource: require('../../../assets/products/ui/categories/jewelry.webp'),
    palette: ['#5B101B', '#D7A84A'],
    icon: 'diamond-outline',
    inputMode: 'SINGLE_PRODUCT',
    promptKey: 'CATEGORY_JEWELRY',
  },
  {
    id: 'electronics',
    name: 'Telefon & Elektronik',
    description: 'Kamera, port ve kasa geometrisini koruyan teknoloji çekimi.',
    creditCost: 0,
    modelLane: null,
    imageSource: require('../../../assets/products/ui/categories/electronics.webp'),
    palette: ['#121722', '#4B6082'],
    icon: 'phone-portrait-outline',
    inputMode: 'SINGLE_PRODUCT',
    promptKey: 'CATEGORY_ELECTRONICS',
  },
] as const satisfies readonly ProductCategory[];

export const productScenes = [
  {
    id: 'white-studio',
    name: 'Beyaz Stüdyo',
    description: 'Temiz e-ticaret kataloğu.',
    creditCost: 5,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/scenes/white-studio.webp'),
    palette: ['#D9D9D7', '#FFFFFF'],
    icon: 'camera-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'PRODUCT_SCENE_WHITE_STUDIO',
  },
  {
    id: 'gray-catalog',
    name: 'Gri Katalog',
    description: 'Nötr gri fonda dengeli ışık.',
    creditCost: 5,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/scenes/gray-catalog.webp'),
    palette: ['#45484E', '#A8ABB0'],
    icon: 'albums-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'PRODUCT_SCENE_GRAY_CATALOG',
  },
  {
    id: 'beige-premium',
    name: 'Bej Premium',
    description: 'Sıcak taş tonlarında rafine sunum.',
    creditCost: 5,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/scenes/beige-premium.webp'),
    palette: ['#8B735C', '#D8C4A9'],
    icon: 'sunny-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'PRODUCT_SCENE_BEIGE_PREMIUM',
  },
  {
    id: 'black-premium',
    name: 'Siyah Premium',
    description: 'Siyah ve altın detaylı lüks sahne.',
    creditCost: 7,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/scenes/black-premium.webp'),
    palette: ['#080808', '#6E5325'],
    icon: 'moon-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'PRODUCT_SCENE_BLACK_PREMIUM',
  },
  {
    id: 'marble',
    name: 'Mermer',
    description: 'Gerçekçi mermer yüzey ve yumuşak gölge.',
    creditCost: 5,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/scenes/marble.webp'),
    palette: ['#8D8176', '#D9D1CA'],
    icon: 'square-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'PRODUCT_SCENE_MARBLE',
  },
  {
    id: 'glass-surface',
    name: 'Cam Yüzey',
    description: 'Kontrollü yansımalı modern vitrin.',
    creditCost: 7,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/scenes/glass-surface.webp'),
    palette: ['#39464F', '#A7D4DC'],
    icon: 'contrast-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'PRODUCT_SCENE_GLASS_SURFACE',
  },
  {
    id: 'floating',
    name: 'Floating',
    description: 'Dengeli, gerçekçi yüzen ürün kompozisyonu.',
    creditCost: 7,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/scenes/floating.webp'),
    palette: ['#756652', '#DED2BC'],
    icon: 'arrow-up-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'PRODUCT_SCENE_FLOATING',
  },
  {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    description: 'Altın vurgulu premium reklam karesi.',
    creditCost: 7,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/scenes/luxury-gold.webp'),
    palette: ['#211507', '#B98222'],
    icon: 'diamond-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'PRODUCT_SCENE_LUXURY_GOLD',
  },
  {
    id: 'neon-tech',
    name: 'Neon Tech',
    description: 'Teknoloji ürünleri için neon gece ışığı.',
    creditCost: 7,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/scenes/neon-tech.webp'),
    palette: ['#26104E', '#087C99'],
    icon: 'flash-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'PRODUCT_SCENE_NEON_TECH',
  },
  {
    id: 'spotlight',
    name: 'Spotlight',
    description: 'Karanlık fonda kontrollü kahraman ışığı.',
    creditCost: 7,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/scenes/spotlight.webp'),
    palette: ['#090909', '#6E6559'],
    icon: 'sunny-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'PRODUCT_SCENE_SPOTLIGHT',
  },
  {
    id: 'spa-beauty',
    name: 'Spa Beauty',
    description: 'Kozmetik için doğal ve hijyenik spa düzeni.',
    creditCost: 5,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/scenes/spa-beauty.webp'),
    palette: ['#58644C', '#D6CDB6'],
    icon: 'leaf-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'PRODUCT_SCENE_SPA_BEAUTY',
  },
  {
    id: 'desktop',
    name: 'Masa Üstü',
    description: 'Gün ışıklı gerçekçi çalışma masası.',
    creditCost: 5,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/scenes/desktop.webp'),
    palette: ['#74563C', '#D6B889'],
    icon: 'desktop-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'PRODUCT_SCENE_DESKTOP',
  },
  {
    id: 'boutique',
    name: 'Butik',
    description: 'Moda ürünleri için sıcak lüks mağaza.',
    creditCost: 7,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/scenes/boutique.webp'),
    palette: ['#4D3827', '#C9985C'],
    icon: 'storefront-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'PRODUCT_SCENE_BOUTIQUE',
  },
  {
    id: 'flat-lay',
    name: 'Flat Lay',
    description: 'Üstten bakışlı düzenli katalog kompozisyonu.',
    creditCost: 5,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/scenes/flat-lay.webp'),
    palette: ['#856F56', '#DCCBB2'],
    icon: 'grid-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'PRODUCT_SCENE_FLAT_LAY',
  },
  {
    id: 'ad-poster',
    name: 'Reklam Poster',
    description: 'Kampanya kullanımı için güçlü hero sahnesi.',
    creditCost: 7,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/scenes/ad-poster.webp'),
    palette: ['#815823', '#E5BF79'],
    icon: 'megaphone-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'PRODUCT_SCENE_AD_POSTER',
  },
] as const satisfies readonly StudioPreset[];

export const fashionScenes = [
  {
    id: 'fashion-white-studio',
    name: 'Beyaz Moda Stüdyosu',
    description: 'Tam kıyafeti gösteren temiz katalog ışığı.',
    creditCost: 8,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/fashion/white-studio.webp'),
    palette: ['#CFC7BC', '#F7F4EF'],
    icon: 'camera-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_WHITE_STUDIO',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-beige-editorial',
    name: 'Bej Editorial Stüdyo',
    description: 'Mimari kıvrımlar ve sıcak gün ışığı.',
    creditCost: 8,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/fashion/beige-editorial.webp'),
    palette: ['#927B65', '#D8C7B5'],
    icon: 'sparkles-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_BEIGE_EDITORIAL',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-luxury-boutique',
    name: 'Lüks Butik',
    description: 'Sıcak raf ışıklı premium moda kampanyası.',
    creditCost: 10,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/fashion/luxury-boutique.webp'),
    palette: ['#15100D', '#9B6D35'],
    icon: 'storefront-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_LUXURY_BOUTIQUE',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-minimal-interior',
    name: 'Minimal İç Mekân',
    description: 'Aydınlık ve sade lifestyle moda karesi.',
    creditCost: 8,
    modelLane: 'PREMIUM',
    palette: ['#9A8D7E', '#DDD6CB'],
    icon: 'home-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_MINIMAL_INTERIOR',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-street-day',
    name: 'Sokak Stili Gündüz',
    description: 'Gün ışığında modern şehir stili.',
    creditCost: 9,
    modelLane: 'PREMIUM',
    palette: ['#526373', '#B8C5CC'],
    icon: 'walk-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_STREET_DAY',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-city-night',
    name: 'Gece Şehir',
    description: 'Islak zemin ve kontrollü neon bokeh.',
    creditCost: 10,
    modelLane: 'PREMIUM',
    palette: ['#170D33', '#8A2F8E'],
    icon: 'moon-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_CITY_NIGHT',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-golden-hour',
    name: 'Golden Hour',
    description: 'Sıcak arka ışıklı açık hava çekimi.',
    creditCost: 9,
    modelLane: 'PREMIUM',
    palette: ['#874525', '#E2AA5B'],
    icon: 'sunny-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_GOLDEN_HOUR',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-hotel-lobby',
    name: 'Otel Lobisi',
    description: 'Taş ve pirinç detaylı lüks editorial.',
    creditCost: 10,
    modelLane: 'PREMIUM',
    palette: ['#2A211D', '#A47C4B'],
    icon: 'business-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_HOTEL_LOBBY',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-runway',
    name: 'Runway',
    description: 'Odaklı podyum ışığında tam görünüm.',
    creditCost: 10,
    modelLane: 'PREMIUM',
    palette: ['#090909', '#55515B'],
    icon: 'flash-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_RUNWAY',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-magazine-editorial',
    name: 'Dergi Editorial',
    description: 'Güçlü kompozisyonlu yüksek moda çekimi.',
    creditCost: 10,
    modelLane: 'PREMIUM',
    palette: ['#342A31', '#A77B88'],
    icon: 'newspaper-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_MAGAZINE_EDITORIAL',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-red-carpet',
    name: 'Red Carpet',
    description: 'Kurgusal gala ve yumuşak flaş fotoğrafı.',
    creditCost: 10,
    modelLane: 'PREMIUM',
    palette: ['#4B0712', '#B32035'],
    icon: 'star-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_RED_CARPET',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-cafe',
    name: 'Kafe Lifestyle',
    description: 'Rahat pozlu sıcak pencere ışığı.',
    creditCost: 9,
    modelLane: 'PREMIUM',
    palette: ['#61422D', '#C39C70'],
    icon: 'cafe-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_CAFE',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-istanbul-street',
    name: 'İstanbul Sokak',
    description: 'Tarihi taş dokulu özgün şehir atmosferi.',
    creditCost: 9,
    modelLane: 'PREMIUM',
    palette: ['#5C493B', '#B38A63'],
    icon: 'location-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_ISTANBUL_STREET',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-modest-premium',
    name: 'Modest Premium',
    description: 'Kapsama ve silueti koruyan zarif kampanya.',
    creditCost: 9,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/fashion/modest-premium.webp'),
    palette: ['#8C7968', '#D8C8B4'],
    icon: 'shield-checkmark-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_MODEST_PREMIUM',
    inputMode: 'PERSON_AND_GARMENT',
  },
  {
    id: 'fashion-event',
    name: 'Düğün / Özel Gün',
    description: 'Yumuşak dekorlu resmi etkinlik çekimi.',
    creditCost: 10,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/fashion/event.webp'),
    palette: ['#252025', '#A98D78'],
    icon: 'rose-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'FASHION_EVENT',
    inputMode: 'PERSON_AND_GARMENT',
  },
] as const satisfies readonly FashionScene[];

export const nailPresets = [
  {
    id: 'nail-nude-clean',
    name: 'Nude Clean',
    description: 'Doğal uzunluğu koruyan parlak nude görünüm.',
    creditCost: 4,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/nails/nude-clean.webp'),
    palette: ['#B88672', '#E8C8B8'],
    swatch: ['#C9A290', '#EBCDBE'],
    icon: 'color-fill-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_NUDE_CLEAN',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-classic-red',
    name: 'Classic Red',
    description: 'Derin ve eşit parlak kırmızı.',
    creditCost: 4,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/nails/classic-red.webp'),
    palette: ['#4D0710', '#B7192B'],
    swatch: ['#710B17', '#D72135'],
    icon: 'color-fill-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_CLASSIC_RED',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-french',
    name: 'French Manicure',
    description: 'İnce beyaz uçlu klasik salon görünümü.',
    creditCost: 5,
    modelLane: 'FAST',
    palette: ['#D8AEB0', '#FAF8EF'],
    swatch: ['#E7BCBE', '#FFFFFF'],
    icon: 'sparkles-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_FRENCH',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-milky-white',
    name: 'Milky White',
    description: 'Yarı saydam süt beyazı parlaklık.',
    creditCost: 4,
    modelLane: 'FAST',
    palette: ['#CFCBC5', '#FFFDF7'],
    swatch: ['#E6E2DA', '#FFFFFF'],
    icon: 'color-fill-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_MILKY_WHITE',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-burgundy',
    name: 'Burgundy Gloss',
    description: 'Sofistike koyu bordo parlaklık.',
    creditCost: 4,
    modelLane: 'FAST',
    palette: ['#260710', '#73142B'],
    swatch: ['#3D0715', '#861A35'],
    icon: 'color-fill-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_BURGUNDY',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-emerald',
    name: 'Emerald Green',
    description: 'Derin zümrüt yeşili salon parlaklığı.',
    creditCost: 4,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/nails/emerald.webp'),
    palette: ['#053727', '#0B8A5C'],
    swatch: ['#064A34', '#12A36D'],
    icon: 'color-fill-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_EMERALD',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-black',
    name: 'Black Gloss',
    description: 'Kenar ayrıntısını koruyan parlak siyah.',
    creditCost: 4,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/nails/black-gloss.webp'),
    palette: ['#050505', '#332D38'],
    swatch: ['#050505', '#423B46'],
    icon: 'contrast-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_BLACK',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-champagne-chrome',
    name: 'Champagne Chrome',
    description: 'Tırnak eğrisini izleyen metalik yansıma.',
    creditCost: 6,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/nails/champagne-chrome.webp'),
    palette: ['#715019', '#E7C46E'],
    swatch: ['#9A742D', '#F1D88E'],
    icon: 'sparkles-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'NAIL_CHAMPAGNE_CHROME',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-soft-pink',
    name: 'Soft Pink',
    description: 'Yumuşak allık pembesi doğal görünüm.',
    creditCost: 4,
    modelLane: 'FAST',
    palette: ['#B8788D', '#EDC1CC'],
    swatch: ['#CF91A5', '#F4CAD4'],
    icon: 'color-fill-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_SOFT_PINK',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-lavender',
    name: 'Lavender Pastel',
    description: 'Yumuşak pastel lavanta rengi.',
    creditCost: 4,
    modelLane: 'FAST',
    palette: ['#705B94', '#C9B7E4'],
    swatch: ['#846EA9', '#D6C5ED'],
    icon: 'color-fill-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_LAVENDER',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-baby-blue',
    name: 'Baby Blue',
    description: 'Nazik ve dengeli açık mavi.',
    creditCost: 4,
    modelLane: 'FAST',
    palette: ['#678EAD', '#C8E0EF'],
    swatch: ['#79A7C8', '#D5EAF5'],
    icon: 'color-fill-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_BABY_BLUE',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-gold-line',
    name: 'Minimal Gold Line',
    description: 'Nude zemin üzerinde ince metalik çizgi.',
    creditCost: 5,
    modelLane: 'FAST',
    palette: ['#927331', '#E1C277'],
    swatch: ['#B28A35', '#F1D989'],
    icon: 'remove-outline',
    hdExtraCredits: 2,
    isPremium: false,
    promptKey: 'NAIL_GOLD_LINE',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-pearl-glazed',
    name: 'Pearl / Glazed',
    description: 'Yarı saydam inci ışıltısı.',
    creditCost: 6,
    modelLane: 'PREMIUM',
    palette: ['#B7A7B9', '#F3E8EF'],
    swatch: ['#D3C4D5', '#FFF2F7'],
    icon: 'ellipse-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'NAIL_PEARL_GLAZED',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-cat-eye',
    name: 'Dark Cat Eye',
    description: 'Kontrollü manyetik ışık şeritli koyu görünüm.',
    creditCost: 6,
    modelLane: 'PREMIUM',
    palette: ['#130B24', '#65347E'],
    swatch: ['#1B0E31', '#8348A0'],
    icon: 'eye-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'NAIL_CAT_EYE',
    inputMode: 'HAND_PHOTO',
  },
  {
    id: 'nail-editorial-gem',
    name: 'Editorial Gem',
    description: 'Az sayıda gerçekçi kristal vurgu.',
    creditCost: 6,
    modelLane: 'PREMIUM',
    palette: ['#8E679A', '#E4C1DF'],
    swatch: ['#B48CC0', '#F1D7EC'],
    icon: 'diamond-outline',
    hdExtraCredits: 2,
    isPremium: true,
    promptKey: 'NAIL_EDITORIAL_GEM',
    inputMode: 'HAND_PHOTO',
  },
] as const satisfies readonly NailPreset[];

export const studioModeCards = [
  {
    id: 'product-shoot',
    mode: 'product',
    name: 'Ürün Çekimi',
    description: 'Reklam ve lifestyle sahnelerinde ürününü öne çıkar.',
    creditCost: 5,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/product-shoot.webp'),
    palette: ['#392814', '#B98942'],
    icon: 'camera-outline',
    defaultSceneId: 'beige-premium',
  },
  {
    id: 'product-catalog',
    mode: 'product',
    name: 'Katalog Çekimi',
    description: 'Cam yüzeyde kontrollü yansımayla modern katalog karesi hazırla.',
    creditCost: 7,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/catalog-shoot.webp'),
    palette: ['#39464F', '#A7D4DC'],
    icon: 'albums-outline',
    defaultSceneId: 'glass-surface',
  },
  {
    id: 'virtual-try-on',
    mode: 'fashion',
    name: 'Kıyafet & Stil',
    description: 'Kıyafeti kendi fotoğrafında gerçekçi biçimde dene.',
    creditCost: 8,
    modelLane: 'PREMIUM',
    imageSource: require('../../../assets/products/ui/fashion-cover.webp'),
    palette: ['#55473B', '#C7AA84'],
    icon: 'shirt-outline',
    defaultSceneId: 'fashion-white-studio',
  },
  {
    id: 'nail-preview',
    mode: 'nails',
    name: 'Tırnak & Manikür',
    description: 'El anatomini koruyarak manikürünü önceden gör.',
    creditCost: 4,
    modelLane: 'FAST',
    imageSource: require('../../../assets/products/ui/nails-cover.webp'),
    palette: ['#4E0712', '#AE1830'],
    icon: 'color-palette-outline',
    defaultPresetId: 'nail-classic-red',
  },
] as const satisfies readonly StudioModeCard[];

export type ProductCategoryId = (typeof productCategories)[number]['id'];
export type ProductSceneId = (typeof productScenes)[number]['id'];
export type FashionSceneId = (typeof fashionScenes)[number]['id'];
export type NailPresetId = (typeof nailPresets)[number]['id'];

export const studioCatalog = {
  productCategories,
  productScenes,
  fashionScenes,
  nailPresets,
} as const;
