import type { ImageSourcePropType } from 'react-native';

export type CatalogKind = 'scene' | 'filter' | 'person' | 'tool';

export type CatalogItem = {
  id: string;
  slug: string;
  name: string;
  subtitle: string;
  kind: CatalogKind;
  category: string;
  palette: readonly [string, string];
  icon: string;
  /** A real visual reference when a catalogue card needs more than an abstract palette. */
  previewSource?: ImageSourcePropType;
  creditCost?: number;
  isPro?: boolean;
  ai?: boolean;
};

export const scenes: CatalogItem[] = [
  {
    id: 'scene-stadium-lights',
    slug: 'stadium-lights',
    name: 'Gece Stadyumu',
    subtitle: 'Işıklar altında güçlü bir kare',
    kind: 'scene',
    category: 'Spor',
    palette: ['#183A4E', '#50621B'],
    icon: '⚽',
    previewSource: require('../../assets/onboarding/images/scenes/stadium.png'),
    creditCost: 1,
  },
  {
    id: 'scene-award-night',
    slug: 'award-night',
    name: 'Ödül Gecesi',
    subtitle: 'Şehir kıyısında ışıltılı bir davet',
    kind: 'scene',
    category: 'Etkinlik',
    palette: ['#57310F', '#B56A17'],
    icon: '✦',
    previewSource: require('../../assets/onboarding/images/scenes/gift.png'),
    creditCost: 1,
  },
  {
    id: 'scene-city-glow',
    slug: 'city-glow',
    name: 'Şehir Işıkları',
    subtitle: 'Gece şehir dokusu',
    kind: 'scene',
    category: 'Şehir',
    palette: ['#27104C', '#135E73'],
    icon: '◈',
    previewSource: require('../../assets/onboarding/images/scenes/light-cities.png'),
    creditCost: 1,
  },
  {
    id: 'scene-coastal-day',
    slug: 'coastal-day',
    name: 'Sahil Günü',
    subtitle: 'Turkuaz koyda Akdeniz terası',
    kind: 'scene',
    category: 'Doğa',
    palette: ['#075B70', '#E2B35B'],
    icon: '☼',
    previewSource: require('../../assets/onboarding/images/scenes/beach.png'),
    creditCost: 1,
  },
  {
    id: 'scene-studio-ink',
    slug: 'studio-ink',
    name: 'Stüdyo Işığı',
    subtitle: 'Pencere ışığında doğal portre',
    kind: 'scene',
    category: 'Portre',
    palette: ['#202020', '#565656'],
    icon: '◐',
    previewSource: require('../../assets/onboarding/images/scenes/portrait-change.png'),
    creditCost: 1,
    isPro: true,
  },
  {
    id: 'scene-neon-future',
    slug: 'neon-future',
    name: 'Neon Gelecek',
    subtitle: 'Neon şehirde sinematik otomobil karesi',
    kind: 'scene',
    category: 'Fantastik',
    palette: ['#3B0E5F', '#2C8BA2'],
    icon: '✧',
    previewSource: require('../../assets/onboarding/images/scenes/neon.png'),
    creditCost: 1,
    isPro: true,
  },
  {
    id: 'scene-alpine-lake',
    slug: 'alpine-lake',
    name: 'Dağ Gölü',
    subtitle: 'Gün batımı, dağlar ve ahşap kulübe',
    kind: 'scene',
    category: 'Doğa',
    palette: ['#18364A', '#E99742'],
    icon: '△',
    previewSource: require('../../assets/onboarding/images/scenes/background-change.png'),
    creditCost: 1,
  },
];

export const filters: CatalogItem[] = [
  {
    id: 'filter-natural',
    slug: 'natural-light',
    name: 'Doğal Işık',
    subtitle: 'Sade, dengeli bir görünüm',
    kind: 'filter',
    category: 'Doğal',
    palette: ['#315F54', '#C7B582'],
    icon: '☀',
    previewSource: require('../../assets/onboarding/images/filters/natural.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-drift',
    slug: 'drift-art',
    name: 'Akışkan Sanat',
    subtitle: 'Canlı renklerle özgün AI stil',
    kind: 'filter',
    category: 'Sanatsal',
    palette: ['#D74673', '#4422A8'],
    icon: '✺',
    previewSource: require('../../assets/onboarding/images/filters/dripart.png'),
    creditCost: 1,
    ai: true,
    isPro: true,
  },
  {
    id: 'filter-pop',
    slug: 'pop-poster',
    name: 'Pop Poster',
    subtitle: 'Grafik, cesur ve parlak',
    kind: 'filter',
    category: 'Sanatsal',
    palette: ['#FF534B', '#FFB703'],
    icon: '▦',
    previewSource: require('../../assets/onboarding/images/filters/popart.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-hdr',
    slug: 'hdr-glow',
    name: 'HDR Glow',
    subtitle: 'Daha net ışık ve doku',
    kind: 'filter',
    category: 'Doğal',
    palette: ['#2B3F59', '#C7843E'],
    icon: '◉',
    previewSource: require('../../assets/onboarding/images/filters/hdr.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-bokeh',
    slug: 'soft-bokeh',
    name: 'Yumuşak Bokeh',
    subtitle: 'Yumuşak arka plan derinliği',
    kind: 'filter',
    category: 'Portre',
    palette: ['#5F243D', '#B78258'],
    icon: '◌',
    previewSource: require('../../assets/onboarding/images/filters/bokeh.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-cinematic',
    slug: 'cinematic-noir',
    name: 'Sinematik',
    subtitle: 'Film hissi veren dramatik tonlar',
    kind: 'filter',
    category: 'Sinematik',
    palette: ['#0F2138', '#775431'],
    icon: '▰',
    previewSource: require('../../assets/onboarding/images/filters/cinematic.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-vintage',
    slug: 'warm-vintage',
    name: 'Vintage',
    subtitle: 'Sıcak ve zamansız doku',
    kind: 'filter',
    category: 'Retro',
    palette: ['#6E3B2D', '#C99B57'],
    icon: '◒',
    previewSource: require('../../assets/onboarding/images/filters/vintage.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-mono',
    slug: 'monochrome',
    name: 'Monokrom',
    subtitle: 'Güçlü siyah beyaz kontrast',
    kind: 'filter',
    category: 'Portre',
    palette: ['#101010', '#8B8B8B'],
    icon: '◑',
    previewSource: require('../../assets/onboarding/images/filters/siyah-beyaz.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-studio',
    slug: 'warm-studio',
    name: 'Sıcak Stüdyo',
    subtitle: 'Yumuşak, profesyonel stüdyo ışığı',
    kind: 'filter',
    category: 'Portre',
    palette: ['#4A302A', '#D99159'],
    icon: '◐',
    previewSource: require('../../assets/onboarding/images/filters/studio.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-cyberpunk',
    slug: 'cyberpunk',
    name: 'Cyberpunk',
    subtitle: 'Özgün neon gece atmosferi',
    kind: 'filter',
    category: 'Sinematik',
    palette: ['#3A1C6D', '#00B8D9'],
    icon: '✧',
    previewSource: require('../../assets/onboarding/images/filters/cyberpunk.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-watercolor',
    slug: 'watercolor',
    name: 'Suluboya',
    subtitle: 'Katmanlı, özgün boya dokusu',
    kind: 'filter',
    category: 'Sanatsal',
    palette: ['#4C8AAA', '#E0AF7A'],
    icon: '✺',
    previewSource: require('../../assets/onboarding/images/filters/watercolor.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-sketch',
    slug: 'sketch',
    name: 'Eskiz',
    subtitle: 'İnce çizgi ve doğal kâğıt dokusu',
    kind: 'filter',
    category: 'Sanatsal',
    palette: ['#4A4543', '#BEB3A4'],
    icon: '✎',
    previewSource: require('../../assets/onboarding/images/filters/sketch.png'),
    creditCost: 1,
    ai: true,
  },
  {
    id: 'filter-cartoon',
    slug: 'cartoon',
    name: 'Cartoon',
    subtitle: 'Özgün, temiz çizgili illüstrasyon',
    kind: 'filter',
    category: 'Sanatsal',
    palette: ['#CD4E45', '#F3BB43'],
    icon: '◉',
    previewSource: require('../../assets/onboarding/images/filters/cartoon.png'),
    creditCost: 1,
    ai: true,
  },
];

/** All people are clearly fictional showcase characters, never real people. */
export const fictionalPeople: CatalogItem[] = [
  {
    id: 'persona-aras',
    slug: 'deniz-aras',
    name: 'Deniz Aras',
    subtitle: 'Kurgusal spor hikâyesi',
    kind: 'person',
    category: 'Kurgusal karakter',
    palette: ['#195982', '#203543'],
    icon: 'DA',
    previewSource: require('../../assets/onboarding/images/demos/demo-01.png'),
    creditCost: 2,
    ai: true,
  },
  {
    id: 'persona-nova',
    slug: 'mira-nova',
    name: 'Mira Nova',
    subtitle: 'Kurgusal müzik evreni',
    kind: 'person',
    category: 'Kurgusal karakter',
    palette: ['#7B1E67', '#EC5E98'],
    icon: 'MN',
    previewSource: require('../../assets/onboarding/images/demos/demo-02.png'),
    creditCost: 2,
    ai: true,
  },
  {
    id: 'persona-kaya',
    slug: 'atlas-kaya',
    name: 'Atlas Kaya',
    subtitle: 'Kurgusal sinema evreni',
    kind: 'person',
    category: 'Kurgusal karakter',
    palette: ['#664213', '#B37938'],
    icon: 'AK',
    previewSource: require('../../assets/onboarding/images/demos/demo-03.png'),
    creditCost: 2,
    ai: true,
  },
  {
    id: 'persona-luma',
    slug: 'luma-veren',
    name: 'Luma Veren',
    subtitle: 'Kurgusal moda hikâyesi',
    kind: 'person',
    category: 'Kurgusal karakter',
    palette: ['#373A74', '#9E7BC3'],
    icon: 'LV',
    previewSource: require('../../assets/onboarding/images/demos/demo-04.png'),
    creditCost: 2,
    ai: true,
  },
  {
    id: 'persona-ela',
    slug: 'ela-serra',
    name: 'Ela Serra',
    subtitle: 'Kurgusal doğa hikâyesi',
    kind: 'person',
    category: 'Kurgusal karakter',
    palette: ['#3D4E2A', '#B78B45'],
    icon: 'ES',
    previewSource: require('../../assets/onboarding/images/demos/demo-05.png'),
    creditCost: 2,
    ai: true,
  },
];

export const aiTools: CatalogItem[] = [
  {
    id: 'tool-gender-change',
    slug: 'gender-change',
    name: 'Cinsiyet değiştirme',
    subtitle: 'Seçtiğin kadınsı veya erkeksi AI görünümü',
    kind: 'tool',
    category: 'AI araçları',
    palette: ['#18151D', '#BBA476'],
    icon: '✧',
    ai: true,
    previewSource: require('../../assets/beauty/gender-change.png'),
  },
  {
    id: 'tool-background',
    previewSource: require('../../assets/onboarding/images/scenes/background-change.png'),
    slug: 'background',
    name: 'Arka plan değiştir',
    subtitle: 'Kendinizi yepyeni bir sahneye taşıyın',
    kind: 'tool',
    category: 'AI araçları',
    palette: ['#31175D', '#7550A4'],
    icon: '◫',
    creditCost: 1,
    ai: true,
  },
  {
    id: 'tool-light',
    previewSource: require('../../assets/onboarding/images/scenes/light-change.png'),
    slug: 'light',
    name: 'Işığı düzelt',
    subtitle: 'Gölgeleri ve sıcaklığı dengeleyin',
    kind: 'tool',
    category: 'AI araçları',
    palette: ['#754517', '#D5A340'],
    icon: '☼',
    creditCost: 1,
    ai: true,
  },
  {
    id: 'tool-portrait',
    previewSource: require('../../assets/onboarding/images/scenes/portrait-change.png'),
    slug: 'portrait',
    name: 'Portre değiştir',
    subtitle: 'Doğal ayrıntıları koruyun',
    kind: 'tool',
    category: 'AI araçları',
    palette: ['#264A58', '#71A7A4'],
    icon: '◎',
    creditCost: 2,
    ai: true,
  },
  {
    id: 'tool-extend',
    previewSource: require('../../assets/onboarding/images/scenes/photo-size-change.png'),
    slug: 'extend',
    name: 'Fotoğrafı genişlet',
    subtitle: 'Yeni bir kadraj oluşturun',
    kind: 'tool',
    category: 'AI araçları',
    palette: ['#52264B', '#9D6086'],
    icon: '↗',
    creditCost: 2,
    ai: true,
  },
];

export const allCatalogItems = [...scenes, ...filters, ...fictionalPeople, ...aiTools];

export const filterCategories = [
  'Tümü',
  'Popüler',
  'Sanatsal',
  'Doğal',
  'Retro',
  'Sinematik',
  'Portre',
];
export const projectCategories = [
  'Tümü',
  'Favoriler',
  'Sahneler',
  'Filtreler',
  'Ürünler',
  'Kıyafet',
  'Tırnak',
];
